version: '3.7'
services:
  dokuwiki:
    container_name: dokuwiki
    image: 'canelrom1/dokuwiki:latest'
    #build:
    #  context: ./src
    #restart: on-failure
    volumes:
      - "./backups/wiki:/var/www/html"
    ports:
      - '80:80'
    environment:
      DEBUG: "1"
      # Apache2
      APACHE_HTACCESS: "0"
      APACHE_HTML_DIR_TMP: "/tmp/blbalb"
      # PHP
      PHP_LIMITS_UPLOAD: "2M"
      # Mail configuration
      SMTP_HOST: "smtp.domain.tld"
      SMTP_PORT: "587"
      SMTP_USER: "user@domain.tld"
      SMTP_PASSWORD: "mypassword"
      SMTP_MAILFROM: "mailfrom@domain.tld"
    healthcheck:
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 0s


# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
