version: '3.7'
services:
  dokuwiki:
    image: 'canelrom1/dokuwiki:latest'
#    build:
#      context: ./src
#   restart: on-failure
    ports:
      - '80:80'
#    volumes:
#      - './dw-conf:/srv/html/conf'
#      - './dw-data:/srv/html/data'
#      - './dw-plugins:/srv/html/lib/plugins'
#      - './dw-tpl:/srv/html/lib/tpl'
    healthcheck:
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 0s


# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
