version: '3.7'
services:
  dokuwiki:
    container_name: dokuwiki
    image: 'canelrom1/dokuwiki:latest'
#   restart: on-failure
    ports:
      - '80:80'
    volumes:
      - 'dw-conf:/var/www/html/conf'
      - 'dw-data:/var/www/html/data'
      - 'dw-plugins:/var/www/html/lib/plugins'
      - 'dw-tpl:/var/www/html/lib/tpl'
    healthcheck:
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 0s

volumes:
  dw-conf:
    driver: local
  dw-data:
    driver: local
  dw-plugins:
    driver: local
  dw-tpl:
    driver: local

# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
