version: '3.7'
services:
  dokuwiki:
    image: 'canelrom1/dokuwiki:latest'
    #build:
    #  context: ./src
    container_name: dokuwiki
    #restart: on-failure
    volumes:
      - 'dokuwiki:/var/www/html'
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:site.local'
      - 'traefik.port=8080'
      - 'traefik.docker.network=traefik_wan'
    healthcheck:
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 0s

volumes:
  dokuwiki:
    name: dokuwiki

# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
