version: '3.7'
services:
  dokuwiki:
    container_name: dokuwiki
    image: 'canelrom1/dokuwiki:latest'
    #build:
    #  context: ./src
    #restart: on-failure
    networks:
      - traefik_wan
    volumes:
      - 'html:/var/www/html'
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:wiki.domain.tld'
      - 'traefik.port=80'
      - 'traefik.docker.network=traefik_wan'
    healthcheck:
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 0s

volumes:
  html:
    name: "dokuwiki"
    driver: local

networks:
  traefik_wan:
    external: True

# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
