FROM canelrom1/apache2-php7:latest

LABEL maintainer="Rom1 <rom1@canel.ch> - CANEL - https://www.canel.ch"
LABEL date="07/11/2018"
LABEL description="Serveur HTTP + PHP7"


EXPOSE 80
EXPOSE 443

ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2"]
